### ISSUE TITLE
Request Feature: Port Next-Nav to Expo Router v2

### ISSUE THREAD

**Issue by selique** [oslabs-beta/Next-Nav#36]
### Description:
I am a software developer with expertise in JavaScript, TypeScript, React, React Native, and Node.js. I have been using the "Next-Nav" library for Next.js, and I would like to propose a feature request to port this library to Expo Router v2.

### Details:

> 
> 1. Current Library Overview:
> Next-Nav is a Visual Studio Code extension that provides functionality for viewing and manipulating projects using the Next.js App Router. It offers features such as loading project routes, displaying routes in a tree view, accessing files in nested routes, and managing routes and files.
> 
> 2. Purpose of Porting:
> The goal of porting Next-Nav to Expo Router v2 is to provide similar functionality and ease of use for Expo projects. Expo Router v2 is a popular routing library used in Expo applications, and having a tool like Next-Nav for Expo Router v2 would greatly benefit developers working on Expo projects.
> 
> 3. Proposed Features for Ported Library:
> Load a project's src/app route in Expo.
> View routes in a legible tree view for Expo Router v2.
> Easily access files in nested routes within Expo.
> Add or remove routes to/from a clearly defined parent route in Expo.
> Add or remove files to/from routes in Expo.
> Display whether routes render on the client side or server side in Expo.

> 4. Implementation Details:
> To port Next-Nav to Expo Router v2, you may need to make adjustments to the codebase to accommodate Expo's project structure and routing conventions. Ensure that the ported library is compatible with Expo's ecosystem.
> 
> 5. Contribution and Open Source:
> Similar to Next.Nav, make the ported library an open-source project and encourage developers to contribute. Create a repository, and follow the open-source contribution guidelines. Allow pull requests from feature branches into the main repository's dev branch.
> 
> 6. Known Issues:
> Document any known issues or limitations specific to the Expo Router v2 version of the library and keep track of them in the README or a separate document.
> 
> 7. Release Notes:
> Keep a record of version updates, bug fixes, and improvements in the release notes to help users stay informed about the progress of the ported library.

By porting Next-Nav to Expo Router v2, you'll provide Expo developers with a valuable tool for managing their projects, and it will contribute to the development community's best practices and clean code standards.

**Comment by jequerubin** [comment]
Hey Selique!

We appreciate the feedback and we're glad you've found use for our tool! What you propose is a very interesting prospect and we thank you for going into great detail of how a port to Expo would be possible. While a port to Expo Router v2 is something we think would be a great addition to our tool, it is not the main focus of Next.Nav at this time. We will definitely keep your suggestion in mind and hope to implement such a feature down the line!
