### ISSUE TITLE
Feature request: focus on a sub-tree of routes

### ISSUE THREAD

**Issue by awmottaz** [oslabs-beta/Next-Nav#43]
In a large application, it would be useful to only look at a sub-tree of routes. Otherwise you can get very overwhelmed with a large graph to navigate.

**Comment by nathanpeel** [comment]
Hi there, 

That's another great suggestion. We are considering such a feature along with the search feature. For now, you can enter the specific path of the folder and view that tree only until we build an updated solution! 

Thanks again for the support.

**Comment by AnatoliySokolov98** [comment]
Pretty much done with this.  Will come out in the next update at the start of the new year.
